version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build: ./docker/nginx
    container_name: "cus_web"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/www/logs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
    networks:
      - frontend
      - backend
    depends_on:
      - app

  app:
    build: ./docker/php
    container_name: "cus_app"
    tty: true
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/www/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Tokyo
    networks:
      - frontend
      - backend

  postgres:
    image: postgres
    container_name: "cus_postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    networks:
      - frontend
      - backend

  pgadmin4:
    image: dpage/pgadmin4:5.5
    container_name: "cus_pgadmin4"
    ports:
      - 8000:80
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: devshark0814@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ss14ds0814
    hostname: pgadmin4
    links:
      - postgres
    restart: always
    networks:
      - frontend
      - backend

volumes:
  postgres_volume:
    external: true
  pgadmin4_volume:
    external: true