<template>
    <div>
        <v-form>
            <v-container>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="氏名"
                            v-model="customer_name"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="氏名_カナ"
                            v-model="customer_name_kana"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-checkbox
                            v-model="sex"
                            label="男性"
                            color="red"
                            value="1"
                            hide-details
                        ></v-checkbox>
                        <v-checkbox
                            v-model="sex"
                            label="女性"
                            color="red"
                            value="2"
                            hide-details
                        ></v-checkbox>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-menu
                            ref="menu"
                            v-model="menu"
                            :close-on-content-click="false"
                            transition="scale-transition"
                            offset-y
                            min-width="auto"
                        >
                            <template v-slot:activator="{ on, attrs }">
                                <v-text-field
                                    v-model="birthday"
                                    label="生年月日"
                                    prepend-icon="mdi-calendar"
                                    readonly
                                    v-bind="attrs"
                                    v-on="on"
                                ></v-text-field>
                            </template>
                            <v-date-picker
                                v-model="birthday"
                                :active-picker.sync="activePicker"
                                :max="
                                    new Date(
                                        Date.now() -
                                            new Date().getTimezoneOffset() *
                                                60000
                                    )
                                        .toISOString()
                                        .substr(0, 10)
                                "
                                min="1950-01-01"
                                @change="save"
                            ></v-date-picker>
                        </v-menu>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="電話番号(家)"
                            v-model="tel_home"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="電話番号(携帯)"
                            v-model="tel_celler"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="メールアドレス"
                            v-model="e_mail"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="郵便番号"
                            v-model="post_code"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="住所"
                            v-model="address"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="住所_カナ"
                            v-model="address_kana"
                        ></v-text-field>
                    </v-col>
                </v-row>
            </v-container>
        </v-form>
        <v-btn @click="clickSend">登録</v-btn>
    </div>
</template>
<script src="./customerCreate.js"></script>
